parameters:
    raven_authentication_provider.class: Misd\RavenBundle\Security\Authentication\Provider\RavenAuthenticationProvider
    raven_listener.class: Misd\RavenBundle\Security\Firewall\RavenListener
    raven_user_provider.class: Misd\RavenBundle\Security\User\RavenUserProvider
    raven_live_service.class: Misd\RavenBundle\Service\LiveRavenService
    raven_test_service.class: Misd\RavenBundle\Service\TestRavenService
    raven_request_listener.class: Misd\RavenBundle\Listener\RavenRequestListener

services:
    raven.security.authentication.provider:
        class: %raven_authentication_provider.class%
        arguments: ['', @raven_service]

    raven.security.authentication.listener:
        class: %raven_listener.class%
        arguments: [@security.context, @security.authentication.manager, %misd_raven.description%, @raven_service]

    raven_user_provider:
        class: %raven_user_provider.class%

    raven_service:
        class: %raven_service.class%

    kernel.listener.raven_request:
        class: %raven_request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9 }
